package com.example.myapplication

data class Station(
    val title: String,
    val uri: String,
)

val onlineRadioStations = arrayOf(
    Station("Phonk (radiorecord)","https://radiorecord.hostingradio.ru/phonk96.aacp"),
    Station("Future Bass (radiorecord)","https://radiorecord.hostingradio.ru/fbass96.aacp"),
    Station("Future House (radiorecord)","https://radiorecord.hostingradio.ru/fut96.aacp"),
    Station("Progressive (radiorecord)","https://radiorecord.hostingradio.ru/progr96.aacp"),
    Station("EDM (radiorecord)","https://radiorecord.hostingradio.ru/club96.aacp"),
    Station("EDM Classics (radiorecord)","https://radiorecord.hostingradio.ru/edmhits96.aacp"),
    Station("Megamix (radiorecord)","https://radiorecord.hostingradio.ru/mix96.aacp"),
    Station("Record (radiorecord)","https://radiorecord.hostingradio.ru/rr_main96.aacp"),
    Station("Russian Mix (radiorecord)","https://radiorecord.hostingradio.ru/rus96.aacp"),
    Station("Супердискотека 90-х (radiorecord)","https://radiorecord.hostingradio.ru/sd9096.aacp"),
    Station("Russian Hits (radiorecord)","https://radiorecord.hostingradio.ru/russianhits96.aacp"),
    Station("Chill-Out (radiorecord)","https://radiorecord.hostingradio.ru/chil96.aacp"),
    Station("Deep (radiorecord)","https://radiorecord.hostingradio.ru/deep96.aacp"),
    Station("Pirate Station (radiorecord)","https://radiorecord.hostingradio.ru/ps96.aacp"),
    Station("Маятник Фуко (radiorecord)","https://radiorecord.hostingradio.ru/mf96.aacp"),
    Station("Рекорд 00-х (radiorecord)","https://radiorecord.hostingradio.ru/200096.aacp"),
    Station("Trancemission (radiorecord)","https://radiorecord.hostingradio.ru/tm96.aacp"),
    Station("Chill House (radiorecord)","https://radiorecord.hostingradio.ru/chillhouse96.aacp"),
    Station("Big Hits (radiorecord)","https://radiorecord.hostingradio.ru/bighits96.aacp"),
    Station("Record Gold (radiorecord)","https://radiorecord.hostingradio.ru/gold96.aacp"),
    Station("Summer Lounge (radiorecord)","https://radiorecord.hostingradio.ru/summerlounge96.aacp"),
    Station("Summer Dance (radiorecord)","https://radiorecord.hostingradio.ru/summerparty96.aacp"),
    Station("Remix (radiorecord)","https://radiorecord.hostingradio.ru/rmx96.aacp"),
    Station("На Хайпе (radiorecord)","https://radiorecord.hostingradio.ru/hype96.aacp"),
    Station("Russian Gold (radiorecord)","https://radiorecord.hostingradio.ru/russiangold96.aacp"),
    Station("Bass House (radiorecord)","https://radiorecord.hostingradio.ru/jackin96.aacp"),
    Station("10's Dance (radiorecord)","https://radiorecord.hostingradio.ru/201096.aacp"),
    Station("VIP House (radiorecord)","https://radiorecord.hostingradio.ru/vip96.aacp"),
    Station("Party 24/7 (radiorecord)","https://radiorecord.hostingradio.ru/party96.aacp"),
    Station("Trance Classics (radiorecord)","https://radiorecord.hostingradio.ru/trancehits96.aacp"),
    Station("Innocence (radiorecord)","https://radiorecord.hostingradio.ru/ibiza96.aacp"),
    Station("House Hits (radiorecord)","https://radiorecord.hostingradio.ru/househits96.aacp"),
    Station("Minimal/Tech (radiorecord)","https://radiorecord.hostingradio.ru/mini96.aacp"),
    Station("TOP 100 EDM (radiorecord)","https://radiorecord.hostingradio.ru/top100edm96.aacp"),
    Station("Tropical (radiorecord)","https://radiorecord.hostingradio.ru/trop96.aacp"),
    Station("Workout (radiorecord)","https://radiorecord.hostingradio.ru/workout32.aacp"),
    Station("House Classics (radiorecord)","https://radiorecord.hostingradio.ru/houseclss96.aacp"),
    Station("D'n'B Classics (radiorecord)","https://radiorecord.hostingradio.ru/drumhits96.aacp"),
    Station("Lo-Fi (radiorecord)","https://radiorecord.hostingradio.ru/lofi96.aacp"),
    Station("Organic (radiorecord)","https://radiorecord.hostingradio.ru/organic96.aacp"),
    Station("Trap (radiorecord)","https://radiorecord.hostingradio.ru/trap96.aacp"),
    Station("Future Rave (radiorecord)","https://radiorecord.hostingradio.ru/futurerave96.aacp"),
    Station("Tech House (radiorecord)","https://radiorecord.hostingradio.ru/techouse96.aacp"),
    Station("Rap Classics (radiorecord)","https://radiorecord.hostingradio.ru/rapclassics96.aacp"),
    Station("Breaks (radiorecord)","https://radiorecord.hostingradio.ru/brks96.aacp"),
    Station("Trancehouse (radiorecord)","https://radiorecord.hostingradio.ru/trancehouse96.aacp"),
    Station("Rap Hits (radiorecord)","https://radiorecord.hostingradio.ru/rap96.aacp"),
    Station("GOA/PSY (radiorecord)","https://radiorecord.hostingradio.ru/goa96.aacp"),
    Station("Dream Dance (radiorecord)","https://radiorecord.hostingradio.ru/dream96.aacp"),
    Station("Black Rap (radiorecord)","https://radiorecord.hostingradio.ru/yo96.aacp"),
    Station("Dream Pop (radiorecord)","https://radiorecord.hostingradio.ru/dreampop96.aacp"),
    Station("Electro (radiorecord)","https://radiorecord.hostingradio.ru/elect96.aacp"),
    Station("Uplifting (radiorecord)","https://radiorecord.hostingradio.ru/uplift96.aacp"),
    Station("Ambient (radiorecord)","https://radiorecord.hostingradio.ru/ambient96.aacp"),
    Station("Neurofunk (radiorecord)","https://radiorecord.hostingradio.ru/neurofunk96.aacp"),
    Station("Dancecore (radiorecord)","https://radiorecord.hostingradio.ru/dc96.aacp"),
    Station("Liquid Funk (radiorecord)","https://radiorecord.hostingradio.ru/liquidfunk96.aacp"),
    Station("Reggae (radiorecord)","https://radiorecord.hostingradio.ru/reggae32.aacp"),
    Station("Latina Dance (radiorecord)","https://radiorecord.hostingradio.ru/latina96.aacp"),
    Station("Eurodance (radiorecord)","https://radiorecord.hostingradio.ru/eurodance96.aacp"),
    Station("Dubstep (radiorecord)","https://radiorecord.hostingradio.ru/dub96.aacp"),
    Station("Technopop (radiorecord)","https://radiorecord.hostingradio.ru/technopop96.aacp"),
    Station("Techno (radiorecord)","https://radiorecord.hostingradio.ru/techno96.aacp"),
    Station("Disco/Funk (radiorecord)","https://radiorecord.hostingradio.ru/discofunk96.aacp"),
    Station("UK Garage (radiorecord)","https://radiorecord.hostingradio.ru/ukgarage96.aacp"),
    Station("Hardstyle (radiorecord)","https://radiorecord.hostingradio.ru/teo96.aacp"),
    Station("Tecktonik (radiorecord)","https://radiorecord.hostingradio.ru/tecktonik96.aacp"),
    Station("Live DJ-sets (radiorecord)","https://radiorecord.hostingradio.ru/livedjsets96.aacp"),
    Station("Midtempo (radiorecord)","https://radiorecord.hostingradio.ru/mt96.aacp"),
    Station("Synthwave (radiorecord)","https://radiorecord.hostingradio.ru/synth96.aacp"),
    Station("Old School (radiorecord)","https://radiorecord.hostingradio.ru/pump96.aacp"),
    Station("Hard Bass (radiorecord)","https://radiorecord.hostingradio.ru/hbass96.aacp"),
    Station("Darkside (radiorecord)","https://radiorecord.hostingradio.ru/darkside96.aacp"),
    Station("Hypnotic (radiorecord)","https://radiorecord.hostingradio.ru/hypno96.aacp"),
    Station("Moombahton (radiorecord)","https://radiorecord.hostingradio.ru/mmbt96.aacp"),
    Station("2-step (radiorecord)","https://radiorecord.hostingradio.ru/2step96.aacp"),
    Station("Groove/Tribal (radiorecord)","https://radiorecord.hostingradio.ru/groovetribal96.aacp"),
    Station("Rave FM (radiorecord)","https://radiorecord.hostingradio.ru/rave96.aacp"),
    Station("Christmas Chill (radiorecord)","https://radiorecord.hostingradio.ru/christmaschill96.aacp"),
    Station("Jungle (radiorecord)","https://radiorecord.hostingradio.ru/jungle96.aacp"),
    Station("Complextro (radiorecord)","https://radiorecord.hostingradio.ru/complextro96.aacp"),
    Station("Гоп FM (radiorecord)","https://radiorecord.hostingradio.ru/gop96.aacp"),
    Station("Rock (radiorecord)","https://radiorecord.hostingradio.ru/rock96.aacp"),
    Station("60's Dance (radiorecord)","https://radiorecord.hostingradio.ru/cadillac96.aacp"),
    Station("70's Dance (radiorecord)","https://radiorecord.hostingradio.ru/197096.aacp"),
    Station("Record 80-х (radiorecord)","https://radiorecord.hostingradio.ru/198096.aacp"),
    Station("Руки Вверх! (radiorecord)","https://radiorecord.hostingradio.ru/rv96.aacp"),
    Station("Веснушка FM (radiorecord)","https://radiorecord.hostingradio.ru/deti96.aacp"),
    Station("Медляк FM (radiorecord)","https://radiorecord.hostingradio.ru/mdl96.aacp"),
    Station("Нафталин FM (radiorecord)","https://radiorecord.hostingradio.ru/naft96.aacp"),
    Station("Гастарбайтер FM (radiorecord)","https://radiorecord.hostingradio.ru/gast96.aacp"),
    Station("Симфония FM (radiorecord)","https://radiorecord.hostingradio.ru/symph96.aacp"),
    Station("Christmas (radiorecord)","https://radiorecord.hostingradio.ru/christmas96.aacp"),
)